### ISSUE TITLE
Change font from Altinn-DIN to Inter

### ISSUE THREAD

**Issue by hannefinnoy** [Altinn/app-frontend-react#1148]
### Description

Felles designsystem uses the font Inter due to better readability than Altinn-DIN (as well as other reasons). Altinn app frontend should also update to Inter.

### Tasks

Swap font to Inter
Visual test - does it look okay?
Solve any issues that are not acceptable

### Acceptance Criterias
We should try to have as few variations of the font as possible. I will probably miss some variants, but in time we should change to DS typography components. Should help making the design more uniform. 

**Headers**
Our headers look a little weird with different font weights. This is a suggestion that wont change them that much, but will be closer to designsystem sizes.
![Skjermbilde 2023-06-21 kl  13 11 42](https://github.com/Altinn/app-frontend-react/assets/33222679/3648fbc5-69dd-43c6-9ef2-caab884d6522)
- [x] All headers have `font-weight: 500`
- [x] H2: `font-size: 1.75rem`
- [x] H3: `font-size: 1.5rem`
- [x] H4: `font-size: 1.25rem`
- [x] Group header (H2, the one that is "referanser" in the testapp) and header for error summary should have same size and weight as standard H2 and summary header (H2) 

**Paragraph and labels** 
- [x] Label, change to `font-weight: 500`
- [x] description should have the same weight as bodytext. Change to `Font-weight: 400`
- [x] description beneath input/legend should have the color defined in the ds: `semantic/text/neutral/subtle``#4B5563`

**Receipt**
- [x] Change title to `font-weight: 500`
- [x] Change "Dine svar" to `font-weight: 500`

**Other**
- [x] Remove monospace variant of inter from textarea. (Let me know if this is a designsystem issue)
- [x] Attachment component bold texts should be reduced to `font-weight: 500`
- [x] summary answers, change to `font-weight: 500`
- [x] Likert title, change to `font-weight: 500`
- [x] Change name beside the user icon to `font-weight: 500`
- [x] Change font color to the same as the design system. Now we have both as we use some components from DS. If this is a larger task we can make a sepparate issue. Change to `semantic.text.neutral.default` `#1E2B3C`
Note: Legend/description for radio and checkboxes will be fixed in the design system

Altinn app frontend uses the Inter font.

**Comment by bjosttveit** [comment]
Setting labels to fontweight 500 will not match with https://digdir.github.io/designsystem/?path=/docs/kjernekomponenter-fieldset--docs

**Comment by bjosttveit** [comment]
I created a new preview release after some updates: https://github.com/Altinn/app-frontend-react/releases/tag/v3.65.1-interpreview
