### ISSUE TITLE
Be able to show repeating groups as cards (mobile version) instead of table

### ISSUE THREAD

**Issue by Febakke** [Altinn/app-frontend-react#1244]
### Description

There has been a suggestion to be able to use the mobile view of the repeating groups on the desktop version as well. The difference between these two is that the desktop version has table and rows to present all the groups. This works well for scenarios where you excpect the user to create several groups. If you only have a few groups, it might be better to have a simpler view as for example the mobile view. 

Also the table view has limited space to present columns with longer labels. There are options to have short versions or hide columns. But might not fit all scenarios. The mobile view design can show longer labels and user input. 

I suggest we look into the needs from different appdevelopers to see why they need this and what they excpect from this view. The mobile view we have to day, could need a little love so that is a little more compact and easier to sepperate the different groups. 

### Additional Information
**Desktop version**
![Skjermbilde 2023-06-09 kl  13 09 45](https://github.com/Altinn/app-frontend-react/assets/33222679/95862339-3824-40b1-8649-ae2fd33fc3f3)

**Mobile version**
![Skjermbilde 2023-06-09 kl  13 09 54](https://github.com/Altinn/app-frontend-react/assets/33222679/b89c3184-1afb-4209-a36d-dccfeb0d5bb6)

### Tasks

- [ ] Gather needs
- [ ] Re-design

### Acceptance Criterias
All basic repeating groups functionality
- [ ] Add and delete group
- [ ] All fields are presented for the user when the card is closed
- [ ] You can open/edit group
- [ ] Handle validation message on a closed group

**Comment by jorgennyborgchr** [comment]
Dette er fra vårt lakselus-rapportering skjema i Mattilsynet:
![image](https://github.com/Altinn/app-frontend-react/assets/124579304/e86d7c8b-90d2-4a9e-baab-3db4fb5b3a2b)
![image](https://github.com/Altinn/app-frontend-react/assets/124579304/1ad4414b-1beb-4d86-a94b-2d1b57d8b460)

**Comment by tvs-brreg** [comment]
I skjema for Reelle rettighetshavere har vi god plass til informasjonen, men det kan absolutt argumenteres for at det er mer oversiktlig med mobilversjonen. Elementene som allerede har blitt lagt til blir uansett tydeligere, noe som faller bort i vanlig tabell visning.

![Skjermbilde 2023-06-12 kl  08 10 32](https://github.com/Altinn/app-frontend-react/assets/126169883/f64cf29e-b208-48ca-9a10-02349175fc0c)
![Skjermbilde 2023-06-12 kl  08 11 33](https://github.com/Altinn/app-frontend-react/assets/126169883/1adf56bc-37ab-42af-b6a9-838aae4a5c6e)


Vi har også en slik gruppe lenger "inn" i skjema. Der, selv med lite informasjon, blir det fort litt trangt med lengre virksomhetsnavn og her vil definitivt mobilvisningen hjelpe med en bedre oversikt.

![Skjermbilde 2023-06-12 kl  08 12 13](https://github.com/Altinn/app-frontend-react/assets/126169883/5f9b1c8d-df8a-4a88-bbc6-021d117de1e2)
![Skjermbilde 2023-06-12 kl  08 11 46](https://github.com/Altinn/app-frontend-react/assets/126169883/99d7707f-f525-4a49-893f-392d48922369)

**Comment by Febakke** [comment]
Radio panel group designet for Altinn 3 has a similar design. We should have this in mind when designing this component.
![Skjermbilde 2023-06-21 kl  10 39 39](https://github.com/Altinn/app-frontend-react/assets/33222679/187d500d-d532-497c-869e-7d6e8dc29f58)

**Comment by rvessb** [comment]
På mobil blir "kortene" (eller radene i tabellen, som det egenltig er) veldig små slik det er i dag. Spesielt ikonet for redigering er lite og det er lite logisk at man ikke bare kan trykke/klikke på selve "kortet" for å åpne det. 
Skjermdumt fra skjema for småviltrapportering:
![image](https://github.com/Altinn/app-frontend-react/assets/43333852/74930608-6178-4499-a8af-84e672dd6e54)

Hva med å se mot designet som er brukt i Innboks i Altinn. Radene/kortene i Innboks er "klikkbare" og det er jo ingen bakdel at designet i skjematejensten er gjenkjennbart fra innboksen.
![image](https://github.com/Altinn/app-frontend-react/assets/43333852/f2f0134a-ec94-471d-b343-272e088a94e1)

Tråd på slack:
https://altinn.slack.com/archives/C02EVE4RU82/p1688385567818409

**Comment by olemartinorg** [comment]
Noen løse tanker etter diskusjon om denne med SSB:
- [ ] En opsjon for å bruke cards/mobilmodus istedenfor full tabell
- [ ] Bytte ut dagens mobilmodus med (den penere) Card-komponenten
- [ ] Klikk på et card bør åpne redigeringsmodus
- [ ] Detektere om man bruker f.eks. Input-komponenter "i tabellen" (i cardet). I disse tilfellene bør klikk på cardet ikke åpne redigeringsmodus. Hvis man har tvunget cards-visningen bør det nok også utelukke all "redigeringsmodus"-funksjonalitet.
