### ISSUE TITLE
As an end-user, I should be able to download the attachment from form in form filling state

### ISSUE THREAD

**Issue by acn-dgopa** [Altinn/app-frontend-react#140]
## Description
As an end user, I might have requirement to download the attachment when i'm in form filling state

## Considerations
Input (beyond tasks) on how the user story should be solved can be put here.

## Acceptance criteria
- It should be possible to download attachment in formfilling state

## Tasks
- [ ] React app must be updated to add possibility to download attachment
- [ ] Service implementation for downloading attachment must be added in DataStudioSI and DataAppSI
- [ ] Documentation (if relevant)
- [ ] Test / QA (if relevant)

**Comment by torbjokv** [comment]
We have a use case where we want to prefill a form including files. It's tricky today because the user can not open the files in any way before sending.

**Comment by FinnurO** [comment]
Dette er mulig i A2.

https://altinn.slack.com/archives/C02FK32FBR6/p1677155313540389?thread_ts=1677155313.540389&cid=C02FK32FBR6

**Comment by sophiearntsen** [comment]
<img width="643" alt="Skjermbilde 2023-05-23 kl  22 08 52" src="https://github.com/Altinn/app-frontend-react/assets/130562196/8493b440-7ab5-4de9-829d-f429b17387ac">

https://www.figma.com/file/Pvti3aRcOwH0k5Z7DrLznk/Arbeidsomr%C3%A5de%3A-Altinn-Studio-APPS?type=design&node-id=4648%3A103870&t=nakXKoXDrY02hiIK-1
