### ISSUE TITLE
If user only have one party to represent, system should change party for end user

### ISSUE THREAD

**Issue by helenekri** [Altinn/app-frontend-react#149]
## Description
For the MVP instantiation flow, we will display the party list if user is currently representing a party that is not meeting the party requirements set on an application. For future instantiation flow we want to explore if the system should suggest / ask for approval to change the current user. The system should ask you if its okay to change to valid party, instead of providing you with the party list (with one option). 

This is recommended to be user tested together with issue Altinn/app-template-dotnet#30 

## Screenshots
> Screenshots or links to Figma (make sure your sketch is public)

## Considerations
Input (beyond tasks) on how the user story should be solved can be put here.

## Acceptance criteria
- What is allowed/not allowed (negative tesing)
- Validations
- Error messages and warnings
- ...

## Tasks
- [ ] Provide issues required for solving this epic
- [ ] Plan user test
- [ ] Complete user test and document findings

**Comment by FinnurO** [comment]
Related to Aktørvalg issues in Studio repo

**Comment by olemartinorg** [comment]
Trying to keep issues to a minimum, so closing this and keeping #268 as the open one.
