### ISSUE TITLE
Improved summary and PDF experience

### ISSUE THREAD

**Issue by olemartinorg** [Altinn/app-frontend-react#1502]
There is a need to improve the existing summary functionality including the PDF in order to meet new requirements, to catch up on existing bugs and feature requests as well as to improve the code base.

While the a summary page, and especially the Summary component, is the main foundation for the PDF, there are also separate improvements needed for PDF that is independent of the Summary component. This epic address the total of changes needed in order to meet customer expectations.

Design for the improvements will be handled in https://github.com/Altinn/app-frontend-react/issues/1744

### Summary component
Right now our `Summary` component is somewhat limited. It is possible to point it at a single component, a non-repeating Group, or a repeating Group component, and if my recollection is correct it will:

- Display a simple value, as typed/selected in the target form component
- Display a static map for the Map component
- Render non-form components as normal (or not show them at all?)
- Render a non-repeating Group as a condensed/compact summary
- Render a repeating group as a condensed/compact summary, but will not render nested repeating groups by default
- Render a repeating group looking like individual fields, and render nested repeating groups as condensed/compact fields if given `largeGroup: true`.

It will however not:
- Render a summary for an entire process step, or a different process step (although the automatic PDF generator will attempt to do that for the current process step)
- Render a summary for an entire page, unless that entire page has been wrapped in a non-repeating Group.
- Render deeper components. If given a Group with a Grid/Group/container component inside of it, the innermost container component will not be rendered, as summaries are not recursive.

At the same time, configuration is somewhat limited, as we allow for the `excludedChildren` and `display` options, but it is not at all easy to wrangle Summary into showing something that makes sense (and looks nice) for a user when you are working on a form with more complex Group and nested structures.

In this issue we should look into the usage of Summary today, talk to service owners, and design and implement a better Summary that could replace the one we have now. That should, at a minimum, include:

- Smarter and better defaults. We should test against real apps and verify that summaries we generate makes sense and looks nice.
- Recursivity by default. It should be possible to point to either a single component/group or an entire page in the app.
- It should be possible to use a single Summary component to make a summary of the entire current process step, without specifying every component ID you want to summarize.
- It should be possible to point a Summary component to a previous process step. App-frontend could fetch the layouts and data model for that step, and render a summary of the data in it, if you have permissions to read that data.
- Overrides should be configured per-child, not for the entire Summary at once. Take inspiration from `tableColumns` in repeating `Group`. It should be possible to render the entire process step summary while at the same time making sure one component deep inside the structure is hidden or hides the 'change' button/bottom border/etc.

This should be a breaking change in the future, but could also be developed alongside non-breaking functionality (either by using feature flags or by implementing a new `Summary2` component meant to replace the older one in a future major version).

### PDF related issues
- [x] https://github.com/Altinn/app-lib-dotnet/issues/787
- [ ] https://github.com/Altinn/app-frontend-react/issues/865
- [x] https://github.com/Altinn/app-frontend-react/issues/1804
- [x] https://github.com/Altinn/app-frontend-react/issues/1805
- [x] https://github.com/Altinn/app-frontend-react/issues/1808
- [x] https://github.com/Altinn/app-frontend-react/issues/2401
- [x] https://github.com/Altinn/app-frontend-react/issues/1589
- [x] https://github.com/Altinn/app-frontend-react/issues/2044
- [x] https://github.com/Altinn/app-frontend-react/issues/2480
- [x] https://github.com/Altinn/app-frontend-react/issues/2191
- [x] https://github.com/Altinn/app-frontend-react/issues/2192
- [ ] https://github.com/Altinn/app-lib-dotnet/issues/368

### Summary related issues
- [x] https://github.com/Altinn/app-frontend-react/issues/2311
- [x] https://github.com/Altinn/app-frontend-react/issues/1655
- [ ] https://github.com/Altinn/app-frontend-react/issues/2471
- [x] https://github.com/Altinn/app-frontend-react/issues/1677
- [x] Altinn/app-frontend-react#366
- [x] https://github.com/Altinn/app-frontend-react/issues/2189
- [x] https://github.com/Altinn/app-frontend-react/issues/1641
- [x] Altinn/app-frontend-react#111
- [x] https://github.com/Altinn/app-frontend-react/issues/2005
- [x] https://github.com/Altinn/app-frontend-react/issues/1553
- [x] Altinn/app-frontend-react#820
- [x] https://github.com/Altinn/app-frontend-react/issues/1666
- [x] https://github.com/Altinn/app-frontend-react/issues/1515
- [x] https://github.com/Altinn/app-frontend-react/issues/1570
- [x] https://github.com/Altinn/app-frontend-react/issues/2188
- [x] https://github.com/Altinn/app-frontend-react/issues/1590
- [x] Altinn/app-frontend-react#834
- [x] https://github.com/Altinn/app-frontend-react/issues/1703

### Component list
- [x] https://github.com/Altinn/app-frontend-react/issues/2055
- [x] https://github.com/Altinn/app-frontend-react/issues/2414
- [x] https://github.com/Altinn/app-frontend-react/issues/2413
- [x] https://github.com/Altinn/app-frontend-react/issues/2389
- [x] https://github.com/Altinn/app-frontend-react/issues/2387
- [x] https://github.com/Altinn/app-frontend-react/issues/2390
- [x] Altinn/app-frontend-react#1265
- [x] https://github.com/Altinn/app-frontend-react/issues/2367
- [x] https://github.com/Altinn/app-frontend-react/issues/2049
- [x] https://github.com/Altinn/app-frontend-react/issues/2050
- [x] https://github.com/Altinn/app-frontend-react/issues/2051
- [x] https://github.com/Altinn/app-frontend-react/issues/2058
- [x] https://github.com/Altinn/app-frontend-react/issues/2052
- [x] https://github.com/Altinn/app-frontend-react/issues/2053
- [x] https://github.com/Altinn/app-frontend-react/issues/2060
- [x] https://github.com/Altinn/app-frontend-react/issues/2061
- [x] https://github.com/Altinn/app-frontend-react/issues/2062
- [x] https://github.com/Altinn/app-frontend-react/issues/2063
- [x] https://github.com/Altinn/app-frontend-react/issues/2087
- [x] https://github.com/Altinn/app-frontend-react/issues/2174
- [x] https://github.com/Altinn/app-frontend-react/issues/2184
- [x] https://github.com/Altinn/app-frontend-react/issues/2185
- [x] https://github.com/Altinn/app-frontend-react/issues/2388
- [x] https://github.com/Altinn/app-frontend-react/issues/2386

### Summary2 component tasks
- [x] https://github.com/Altinn/app-frontend-react/issues/2070
- [ ] Docs: remove layoutSetID
- [ ] Docs: explain overrding components on a page
- [ ] Docs: update isCompact explanation

**Comment by xmrsa** [comment]
I have added a relevant issue to this, regarding the placement of the "Endre"/"Change"-button in the layout of summaries of Group-components.  https://github.com/Altinn/app-frontend-react/issues/1641

**Comment by madsenandreas** [comment]
**Situation:**
A component of type "Summary" linked by "componentRef" to a "Group" component displays "Du har ikkje lagt inn informasjon her" to a subcomponent in the group even if the user have not used the component which can confuse the person filling the form out.

**Wished Situation**
Components not used in a group will not be displayed in the summary component.

**My Case**
In my case the group has dynamics which shows different components depending on prior choices in the group. The picture below has one component "Fag" with choices "Ingen", Grunnleggende..." this is optional to fill out. It also has a component "Matematikk deltakelse" this is also optional. The applicant can attend both or just one of these. The issue arises when just one of these is selected then the second one in summary gets the text "Du har ikkje lagt inn informasjon her".

![image](https://github.com/Altinn/app-frontend-react/assets/32479865/2d7800ac-898d-40ac-a75c-d2758be195d2)

How the summary component will look like:
![image](https://github.com/Altinn/app-frontend-react/assets/32479865/0d237101-c7df-443d-be75-b261f43d1a41)

**Comment by olemartinorg** [comment]
Relevant discussion:
- https://altinn.slack.com/archives/C02EJ9HKQA3/p1706876059347139

**Comment by olemartinorg** [comment]
Closing as done. The Summary2 component has been out for a while now.
