### ISSUE TITLE
Rewrite fetching sagas to use Tanstack Query

### ISSUE THREAD

**Issue by olemartinorg** [Altinn/app-frontend-react#1509]
These sagas should be rewritten to use Tanstack query. All of them seem fairly straight-forward.

Dynamics:
- [x] fetchDynamicsSaga
- [x] fetchRuleModelSaga

Layout, layout-sets, layout settings:
- [x] fetchLayoutSaga (underway in #1511)
- [x] fetchLayoutSettingsSaga (underway in #1511)
- [x] watchFetchFormLayoutSettingsSaga (underway in #1511)
- [x] fetchLayoutSetsSaga

Party:
- [x] getPartiesSaga
- [x] getCurrentPartySaga

Text resources:
- [x] fetchTextResources
- [x] watchFetchTextResourcesSaga
