### ISSUE TITLE
Support in Altinn Studio for making an app without App-Frontend

### ISSUE THREAD

**Issue by mariavar** [Altinn/app-frontend-react#158]
## Description
We need to make sure that we support creating apps that will not have any App-Frontend as part of the app.  This is relevant when an app is ment to only be used from external API clients.  

For Sirus this is relevant since all interaction is done through APIs.

## PO Statement
This EPIC is related to Sirius who will create an app which shall only be available for end user systems through APIs. As this is the first app that will only be available to submit through API we need to have a look at how the user experience will be for creating apps without API. It is unknown how many apps that will be created without front end at this point, but it is expected that more apps will have this feature going forward.

## Tech statement
The app-architecture we have now is very limited, and it is limited because we've optimized the app code structure for "Studio UI first". This needs to be changed to an approach where Controllers, startup, etc. are part of the apps, so that APIs, CORS, auth, etc. can be added and tested/debugged directly by app developers.

## Considerations
- Should a developer choose actively when creating a new app what kind of template he want to create? Answer: Yes, in time, but not in Studio UI for MVP since api apps will be created by programmers in the short term.
- How are app logic accessed when not having App-Frontend? Answer: Through API.
- How can App-Frontend be added at a later stage. Answer: Add the missing files.
- Does it matter for App-Backend? Answer: Yes, app-backend needs drastic changes.

## Acceptance criteria
- Flow for creating a API-app is defined (api with only backend)
- Defined what kind of files that can be edited and are available. (no point enabling dynamics)

## Tasks
- [ ] Verify that this issue meets DoP (remove unused text, add missing text/parameters/labels, verify tasks).

## Specification tasks
- [ ] Test design / decide test need

## Development tasks
- [ ] Documentation (if relevant)
- [ ] Manual test (if needed)
- [ ] Automated test (if needed)

**Comment by olemartinorg** [comment]
This has been deprioritized as of lately, and Studio is more and more bound to the implementation of features in app-frontend. It is fully possible to create a custom frontend app to replace the default app-frontend (as is being done in OED), but when doing so it makes little sense to still use parts of Studio. Closing this for now.
