### ISSUE TITLE
Make it possible to change language in an application

### ISSUE THREAD

**Issue by helenekri** [Altinn/app-frontend-react#160]
## Description
Depending on results in Altinn/app-frontend-react#154 (and possibly Altinn/app-frontend-react#163), this issue is for implementing the design and specs.
If Altinn/app-frontend-react#163 is not complete, we add language selection with writing selected language to local storage.

## Acceptance criteria
- All languages available should be possible to select
- If changing language, the application should be updated with the new language
- More to come...

## Tasks
- [ ] Decide how we should technically handle displaying different languages (solution) 
- [ ] Design how all options should be available
- [ ] Evaluate if we need a setting in Altinn Studio for languages related to the header or if this is "automagic" based on the added languages
- [ ] Add technical specifications and tasks

**Comment by TheTechArch** [comment]
Closes this since been solved in other issue
