### ISSUE TITLE
Analysis: Handle languages when moving between Altinn.no and an application

### ISSUE THREAD

**Issue by helenekri** [Altinn/app-frontend-react#163]
## Description
When navigating in Altinn.no there is a default language set or you have changed the language to your preferrer language. 
We need to analyse how we should handle language when: 
- Moving from Altinn.no to an application
- Moving from an application back to Altinn.no

### Storing language selection
We need to answer:
- Should we write selected language as preferred when swapping language in app?
  - If so; How do we handle user selecting a language without support in altinn.no?
  - If not; not even for users who go straight to app after first login?

### Fallback languages
We need to handle different scenarios: 
- Moving from Altinn.no with bokmål, nynorsk or english and opening an app which also is available in the same language. 
- Moving from Altinn.no with bokmål, nynorsk or english and the app does not have the language available. Which language should the application default open in?
- Moving from an application where you have another language than what is handled in altinn.no. E.g filling out an application in swedish, how and which language should you get on an altinn.no page. 

## Tasks
- [ ] Analyse how we can technically and functionally support language changes
- [ ] Find out how to handle moving between platform and app if current language is not supported in either app or platform. 
- [ ] If any design is needed - design and specify this
- [ ] Add technical specification and tasks
