### ISSUE TITLE
Language changes should be possible to set in an app

### ISSUE THREAD

**Issue by helenekri** [Altinn/app-frontend-react#164]
## Description
There is a need to look into on which pages (instantiation, fill out service and receipt page) it should be possible to change between languages in an application. 
If a service have added more than "bokmål" to the service, it needs to be possible to select this in the application. 

The language you have selected should default be the language that the user have when starting an application. 

## This epic is completed when: 
- [ ] Changing language within an app is implemented and possible to change from all pages specified to have the functionality
- [ ] Languages other than Bokmål, Nynorsk and English can be used
- [ ] The functionality has been tested
- [ ] The end user have the same language in an app (as long as the app is available in the selected language) as the end user had on the previous page

## For analysis
- [ ] Writing language selection to profile when changing?
  - [ ] Fallback language if not BM/NN/EN? Last selected or EN by default?
  - [x] First version writing selection to local storage? Yes!

## Tasks
- [ ] Specify all issues within the epic
