### ISSUE TITLE
Analysis: Ability to override app navigation and use my own theming

### ISSUE THREAD

**Issue by TheTechArch** [Altinn/app-frontend-react#168]
## Description
As a developer i want that the navigation menu in my app matches the menu in my orgs portal.
I'd also like to override the css to make the form/content look more like my own.

## In scope
- [ ] How much should be easy to override (without having to use a custom front end Altinn/app-frontend-react#195) 

## Out of scope
TBA

## Analysis
TBA

## Conclusion
TBA

## Tasks
- [ ] Is this issue labeled with a correct area label?
- [ ] QA has been done

**Comment by FinnurO** [comment]
Dette er gammelt og overflødig, Theming dekkes i designsystemet. Lukkes.
