### ISSUE TITLE
As a developer I want to edit the receipt text in Altinn Studio

### ISSUE THREAD

**Issue by Febakke** [Altinn/app-frontend-react#171]
## Description
As a developer I would like to change the receipt text in Altinn Studio.

The receipt text is the text the end-user is presented with after submitting the service. It is visible on the receipt page and on messages in the inbox.

Standard text defined in Altinn/altinn-studio#1677 

## Suggested solution
We start by defining that the _app_ receipt can contain custom, possibly more dynamic, data, while the _inbox_ receipt view is strictly static. 

### Step 1
- We support defining the _app_ receipt view via layouts, in the same way as f.eks. the confirm page. This will allow app developers to set up exact texts and other components they choose.
  - We could potentially make it even simpler, and just support a markdown template. This would probably be easier to persist to other parts of the solution if we want to show the receipt other places like inbox.
  - Either way we should support some standard components for displaying metadata and any file attachments incl. receipt pdf.
  - In the _inbox_ receipt, user is just shown a static page which lists out metadata + attachments + pdf receipt.
    - if we do go for a markdown receipt definition, we could persist the _static_ version with the instance and potentially display it together in the _inbox_ receipt view.

### Step 2
- We look into how we can make the messagebox receipt richer:
  - can we show the receipt view directly in the message box view instead of linking to it?
  - Could we leverage the existing correspondence functionality?
    - f.ex. provide the A3 inbox data on correnspondence format, so that we have the details directly available in the inbox item?
    - automatically create a corresponcence for the user with the receipt, and not show the instance itself? This would mean that the user cannot f.ex. create a copy of an archived instance.

## Screenshots
> Screenshots or links to Figma (make sure your sketch is public)

## Considerations
Where should this functionality be presented to the user?
Should we have any restrictions? (text length?)

## Acceptance criteria
- What is allowed/not allowed (negative tesing)
- Validations
- Error messages and warnings
- ...

## Tasks
- [ ] Verify that this issue meets DoP (remove unused text, add missing text/parameters/labels, verify tasks).

## Specification tasks
- [ ] Look into if there should be any restrictions
- [ ] Test design / decide test need

## Development tasks
- [ ] Documentation (if relevant)
- [ ] Manual test (if needed)
- [ ] Automated test (if needed)
- [ ] Design review

**Comment by FinnurO** [comment]
Link til noen relevante diskusjoner i Slack: 
https://altinn.slack.com/archives/C02ESDSJN2H/p1654772134038119 (OED) 
https://altinn.slack.com/archives/C02EVE4TKA6/p1652945472034969 (UDIR)
https://altinn.slack.com/archives/C02EJ9HKQA3/p1649415312718049 
https://altinn.slack.com/archives/C02EVE4RU82/p1648029714728899 (SSB)
https://altinn.slack.com/archives/C02ESDT071T/p1646308315768749 (SVV)
https://altinn.slack.com/archives/C02ESDSTVGD/p1645515674807929 (SKD; endring av tekst)
https://altinn.slack.com/archives/C02FK32PVFS/p1608558618025700 (NBIB)
https://altinn.slack.com/archives/C02EJ9HKQA3/p1641469474003300 (SKD)
https://altinn.slack.com/archives/C02EVE4EXQA/p1628509786011200 (DIBK)
https://altinn.slack.com/archives/C02FK32FBR6/p1613993657006400 (DAT)

**Comment by lasseklovstad** [comment]
Hei! Dette issuet ser ut som noe Elevundersøkelsen hos Udir har behov for. 

**Bakgrunn:**
Elevundersøkelsen er et spørreskjema for elever om trivsel på skolen. Undersøkelsen er anonym og gjennomføres kun en gang per elev.
Etter at undersøkelsen er levert ikke eleven behov for å gjøre noe annet enn å logge ut.
Det kan hende flere elever gjennomfører undersøkelsen på samme datamaskin, det er derfor viktig å kunne enkelt logge ut og at andre elever ikke kan se hverandres besvarelser.

**Behov:**
En egendefinert kvitteringsside med mulighet for å legge til tekst, bilder og en lett synlig logg ut knapp.
Bilder og tekst bør kunne endres/skjules basert på hvilken klasse eleven går i.

**Løsning:**
Dette likner en del på Stateless konseptet.
Kvitteringssiden kan defineres som en FormLayout hvor det kun er lov å benytte statiske komponenter: Header, Image, Paragraph, Panel, PrintButton
Ittillegg ønsker man en ny komponent med navn LogoutButton som brukeren kan trykke på og logge ut.
Det kan også vurderes om listen med Pdf skal da gjøres om til en komponent som da kan velge å bruke eller ikke.

Med denne løsningen kan man lage en egendefinert kvitteringside etter innlevering. Noen tanker?

**![kvitteringsside](https://user-images.githubusercontent.com/43168787/185369347-f8e0d203-9c04-4608-93a2-2d2c5c072c19.png)**

**Comment by knut-olav-hoven-ske** [comment]
Skatteetaten ønsker å ha en slik konfigurasjon i `resource.nb.json` for å sette opp en lenke på kvitteringssiden:

```
    {
      "id": "receipt_platform.helper_text",
      "value": "..... <a href='{0}/web/skattemelding-visning/altinn?appId={0}&instansId={1}' target='_blank'>Se opplysninger som er mottatt</a>",
      "variables" : [
       {
          "key": "homeBaseUrl",
          "dataSource": "applicationSettings"
        },
        {
          "key": "appId",
          "dataSource": "instanceContext"
        },
        {
          "key": "instanceId",
          "dataSource": "instanceContext"
        }
      ]
    }
```

Fra tt02:
Kvittering fra Altinn3-appen som ligger i meldingsboksen:
![Altinn3 app kvittering fra app grønn](https://user-images.githubusercontent.com/84783397/187211184-51f538e0-2054-499e-ac7c-acf45afa6c16.png)

Kvittering fra arkivet:
![Altinn3 app kvittering fra arkiv blå](https://user-images.githubusercontent.com/84783397/187211254-f4edb493-de08-440d-9d68-922df97c1316.png)

Ideelt sett burde disse to skjermbildene vært mest mulig like.
Primært så ønsker vi en tilsvarende "Se opplysninger som er mottatt"-lenke i appens egen kvitteringsside.
