### ISSUE TITLE
Design for Summary 2.0 component in Altinn 3 

### ISSUE THREAD

**Issue by olavflar** [Altinn/app-frontend-react#1744]
### Description
https://github.com/Altinn/app-frontend-react/issues/1502

Right now our Summary component is somewhat limited. It needs some love from the design team, and this epic is the  "summary" of all the related issues we want to research and explore. 

The summary component is also the main component used when generating PDF's and hence we should have the PDF perspective in this epic as well.

```[tasklist]
### Related issues
- [x] https://github.com/Altinn/app-frontend-react/issues/834
- [x] https://github.com/Altinn/app-frontend-react/issues/1001
- [x] https://github.com/Altinn/app-frontend-react/issues/111
- [x] https://github.com/Altinn/app-frontend-react/issues/1502
- [x] https://github.com/Altinn/app-frontend-react/issues/1515
- [x] https://github.com/Altinn/app-frontend-react/issues/1553
- [ ] https://github.com/Altinn/app-frontend-react/issues/1590
- [ ] https://github.com/Altinn/app-frontend-react/issues/1641
- [ ] https://github.com/Altinn/app-frontend-react/issues/1655
- [ ] https://github.com/Altinn/app-frontend-react/issues/1677
- [ ] https://github.com/Altinn/app-frontend-react/issues/1661
- [ ] https://github.com/Altinn/app-frontend-react/issues/1666
- [ ] https://github.com/Altinn/app-frontend-react/issues/1265
- [ ] https://github.com/Altinn/app-frontend-react/issues/1703
- [ ] https://github.com/Altinn/app-lib-dotnet/issues/787
```
```[tasklist]
### Design tasks
- [ ] https://github.com/Altinn/app-frontend-react/issues/1780
- [ ] https://github.com/Altinn/app-frontend-react/issues/1781
- [ ] https://github.com/Altinn/app-frontend-react/issues/1782
- [ ] https://github.com/Altinn/app-frontend-react/issues/1783
- [ ] https://github.com/Altinn/app-frontend-react/issues/1784
- [ ] https://github.com/Altinn/app-frontend-react/issues/1785
- [ ] https://github.com/Altinn/app-frontend-react/issues/1786
- [ ] https://github.com/Altinn/app-frontend-react/issues/1954
- [ ] https://github.com/Altinn/app-frontend-react/issues/1955
- [ ] https://github.com/Altinn/app-frontend-react/issues/2116
- [ ] Tabs component for summary and PDF
```
