### ISSUE TITLE
Design relaterte oppgaver til Samhandlingstjenester i Altinn 3

### ISSUE THREAD

**Issue by olavflar** [Altinn/app-frontend-react#1755]
Bakgrunn for Samhandlingstjenester i Altinn 3:
https://github.com/digdir/roadmap/issues/83

As is brukerreise: 
[Konkursbo-brukerreise-.pdf](https://github.com/Altinn/app-frontend-react/files/15059094/Konkursbo-brukerreise-.pdf)

```[tasklist]
### Tasks
- [ ] https://github.com/Altinn/app-frontend-react/issues/1757
- [x] Samarbeid med BR om konkursbo
- [x] Kartlegge dagens løsning med brukerreise
- [x] Lage skisser til brukerreisen
- [x] Godkjenne brukerreise med resten av Team Apps & Studio og Bjørn Langfors
- [x] Presentasjon av skisser for hvordan konkursbo kan bli i Altinn 3 med Tjenesteeier
- [x] Lage ferdig skisser og issues som er klare til utvikling
```
