### ISSUE TITLE
Look into upgrading how app specific information is presented in our header

### ISSUE THREAD

**Issue by Febakke** [Altinn/app-frontend-react#178]
## Description
Our apps are getting more and more functionality, way beyond what was intended in the original design of the modal view we have today. In some future example we see that the space is getting cramped, is there anything we can do with the general design to hinder this? In a way we have two headers today. Our top "menu/header" shows the Altinn logo and who you are logged in as. (In the future also language will be chosen from here?) At this time we look at these elements as global, they do not change depending on what application the user is accessing. 

Inside the modal we have the app specific information. The name of the app and the app owner name. This is were we are putting in more features making it more cramped. This is the main content of the app and should be given space. Is there something we can do give the app specific elements more space? 

**Element to assess**
* App owner logo as a part of the global header?
* A lot of space between modal and header, are there other ways we structure it to give more focus to the main content?
* Expand design of modal or look into other ways of presenting the app specific information. 

## In scope
How will our current design hold up with future features being introduced?
Do our global / app specific information make sense how it set up today? 

## Tasks
- [ ] Research similar "powered by" solutions. How do they show the app owner / Platform owner
- [ ] How does the global header function today? Is it useful or just there because thats how the original design was?
- [ ] Map out the functionality and information that will most often be present in our apps. What is most important and should have focus?
