### ISSUE TITLE
Udir will use Altinn as a survey-engine for 450 000 school kids

### ISSUE THREAD

**Issue by pckofstad** [Altinn/app-frontend-react#181]
# Top-level project description of Utdanningsdirektoratets project using Alltinn 3 as a survey engine

## Introduction
Utdanningsdirektoratet has decided to use Altinn Studio 3 as the response plattform to serve the survey "Elevundersøkelsen". This survey is answered by about 450 000 kids every year. The response period is within 3-12 weeks (to be decided). All survey questions must be possible to edit dynamically by employees in utdanningsdirektoratet. The design must be student/child friendly. 

## In scope for this epic description
The schope will change slightly during the development of the project. 

### [Language changes should be possible to set in an app #164](https://github.com/Altinn/app-frontend-react/issues/164)
We want to be able to change the language for the users taking the survey, without leaving the survey |
- [ ] [Altinn Studio PR](https://github.com/Altinn/altinn-studio/pull/8483) - PR created: 23/5/2022 
- [x] [Altinn dotnet template PR](https://github.com/Altinn/app-template-dotnet/pull/85) - PR created: 23/5/2022 
- [ ] [Altinn frontend PR](https://github.com/Altinn/app-frontend-react/pull/83) - PR created: 23/5/2022 
- [ ] [Altinn docs PR](https://github.com/Altinn/altinn-studio-docs/pull/516) - PR created: 6/5/2022 
- [ ] [Altinn cdn PR](https://github.com/Altinn/altinn-cdn/pull/96) - PR created: 11/5/2022 

### "Likert" grouping of questions [No issue created]
We want to "radiobutton" and "checkbox" answer questions together in tighter UI groups. This is in order to make it easier to answer many questions easily, and to make it look more compact and structured. 
- [ ] [Altinn frontend PR](https://github.com/Altinn/app-frontend-react/pull/72) - PR created: 24/5/2022 
- [ ] [Altinn studio PR](https://github.com/Altinn/altinn-studio/pull/8441) - PR created: 28/4/2022 
- [ ] [Altinn cdn PR](https://github.com/Altinn/altinn-cdn/pull/95) - PR created: 4/5/2022 
- [ ] [Altinn studio docs PR](https://github.com/Altinn/altinn-studio-docs/pull/506) - PR created: 4/5/2022 

### Enabeling "custom claims" for users when doing local development [No issue created]
We are using authentication by UIDP and need to emulate and test with different claims coming from UIDP.
- [x] [Altinn studio PR](https://github.com/Altinn/altinn-studio/pull/8434) - PR created: 8/5/2022 

### [As a user I would like to see my progress in the application #4636](https://github.com/Altinn/altinn-studio/issues/4636)
The survey could have somewhere between 10-15 pages, we would like the users to see how many pages they have left to answer in a  visual and easy understandable way. 
- [ ] No PR created yet. 

### Ability to unselect selected radiobutton / checbox answer [No issue created]
It is a strong requirement that you don't have to answer any question in the survey if you don't want to. This requirement is also understud as "the ability to unselect an already selected answer". 
- [ ] No PR created yet. 

### Ability to design a custom "delivered sucsessfully" page [No issue created]
We need to build a custom "deliverd sucsessfully" page that is more kids friendly that the reciept page that is shown as standard. We have not a complete design for the page yet, but the support for adding images and links to other pages is out current hypothesis.  
- [ ] No PR created yet. 

### Ability to logout of the survey directly from the survey [No issue created]
The survey will need to have look and feel of a standalone app. In order to reduce confusion we never want any students to have to close the survey and see the "inbox view" in Altinn in order to do any operations. This includes changing languages (see separate PR) and the ability to sign out of the survey/altinn from within the survey. 
- [ ] No PR created yet. 

## Out of scope for this epic description
The in-depth descriptions the parts of the survey platform that is not using Alltinn studio.

**Comment by FinnurO** [comment]
Duplikat av https://github.com/Altinn/apps-backlog/issues/4 ?

**Comment by pckofstad** [comment]
> Duplikat av [Altinn/apps-backlog#4](https://github.com/Altinn/apps-backlog/issues/4) ?

Dette er en beskrivelse og oppsamling av elementer for hele "survey engine" prosjektet. Den refererte linken ser jeg som beskrivelse av påloggings tilpassningen som ble laget sommer/høsten 2021.
