### ISSUE TITLE
Unique IDs in repeating groups

### ISSUE THREAD

**Issue by olemartinorg** [Altinn/app-frontend-react#1812]
### Introduction
After the JsonPatch change, and the new form data engine in v4, combined with `openByDefault` actually creating objects for automatically added rows, it's becoming obvious that we need some better way to uniquely differentiate between repeating groups rows than the indexes alone.

After a meeting the 9th of February 2024, with participants from Apps and Studio, we landed on a proposed solution where Studio generates partial classes in data models (and the CLI tool to upgrade existing apps rewrites the models to partial), while the backend uses a source generator to extend the classes with our own metadata/values. This should allow for unique IDs to be added, serialized and stored in Storage, and kept all the way through form filling.
```[tasklist]
### Tasks
- [ ] https://github.com/Altinn/app-lib-dotnet/issues/435
- [ ] https://github.com/Altinn/altinn-studio-cli/issues/23
- [ ] https://github.com/Altinn/altinn-studio/issues/12277
- [ ] https://github.com/Altinn/app-frontend-react/issues/1750
- [ ] https://github.com/Altinn/app-lib-dotnet/pull/441
```
