### ISSUE TITLE
Vise innboks fra brukerflate (dialogporten) i en Altinn 3 applikasjon

### ISSUE THREAD

**Issue by RonnyB71** [Altinn/app-frontend-react#1957]
## Beskrivelse
Dagens arbeidsflate i Konkursbo løsningen har en visning av Altinn Innboks med elementer knyttet til et konkursbo. Meldingene som vises hentes ut basert på en såkalt CaseId i Altinn 2, men som i dialogporten løses med External Reference som da vil være organisasjonsnummeret til konkursboet.

![Image](https://github.com/Altinn/app-frontend-react/assets/5430430/f99f888f-9a11-4447-a3ff-fb4f5dc3bb57)

Vi har behov for en tilsvarende visning hvor Brukerflaten til Dialogporten viser alle dialoger knyttet til konkursboets organisasjonsnummer. Skissen under viser hvordan dette kan være, men er ikke endelig.

Link til skisser i Figma; https://www.figma.com/design/6dXNs3Ncbg9dJoK98qyZhV/Dashboard%2FSamhandlingstjeneste-i-Altinn?node-id=296-33959&m=dev
![Image](https://github.com/Altinn/app-frontend-react/assets/5430430/4dc2ad88-2836-4429-bdd7-6bf92e4b4499)

## Ønsket løsning
En ny komponent i Altinn Studio og Apps som kan vise data fra innboksen til konkursboet hvor man kan sende inn dynamisk organisasjonsnummer som skal benyttes som filter.

## Akseptansekrav
- [ ] Konkursboets organisasjonsummer må kunne settes dynamisk og benyttes som filter for de data som skal hentes ut fra Dialogporten.
- [ ] Visningen bør være standard visning slik den er i brukerflaten ellers for gjenkjennbarhet om brukeren skulle åpne bare innboksen.
- [ ] Komponenten må kunne settes opp i Altinn Studio

## Gjennomføring
```[tasklist]
### Oppgaver
```

**Comment by cammiida** [comment]
De ønsker ikke innboksvisning i arbeidsflaten.
