### ISSUE TITLE
Visning av data uten definert datamodell

### ISSUE THREAD

**Issue by RonnyB71** [Altinn/app-frontend-react#2088]
## Beskrivelse
Visning av data krever i dag at det finnes en kjent datamodell definert i appen. For data som i utgangspunktet bare hentes fra eksterne api'er hadde det vært nyttig å kunne konfigurere stien til aktuelle felter direkte i en visningskomponent. 

## Ønsket løsning
Eksemplet under viser en visningskomponent som kunne vært grid komponenten med ulike verdier som kunne vært hentet direkte fra en Json struktur. Et annet alternativ hadde vært å definere et card i stedet for en grid. Det må da være mulig å definere en visningskomponent som står for selve api kallet og hva som inngår. Ideelt sett skulle dette vært løst på samme måte som for #1984. 

![Image](https://github.com/Altinn/app-frontend-react/assets/5430430/1aaaa28e-9e17-4ecf-9619-32fd3ff1a8cb)

## Akseptansekriterier

```[tasklist]
### Tasks
- [ ] https://github.com/Altinn/app-frontend-react/issues/2170
- [ ] https://github.com/Altinn/app-frontend-react/issues/2179
- [x] Date Component
- [x] Handle data without a defined datamodel
- [ ] https://github.com/Altinn/app-lib-dotnet/issues/698
- [ ] https://github.com/Altinn/app-frontend-react/issues/2207
```

**Comment by bjosttveit** [comment]
Fant denne på SSB sin ønskeliste, ikke det samme, men jeg vil si den er relatert siden den handler om å vise data ikke direkte fra datamodell https://github.com/Altinn/app-frontend-react/issues/1178
