### ISSUE TITLE
Rollestyrt visning av et layout set

### ISSUE THREAD

**Issue by RonnyB71** [Altinn/app-frontend-react#2089]
## Beskrivelse
Det er behov for å kunne rollestyre hvilket layoutset som benyttes til visningen av et gitt steg. I tilfellet Konkursboløsningen til Brønnøysundregistrene vil det være ulik visning for rollene bostyrer og kreditor, men prosessteget er det samme. Hvis man har tilgang til prosessteget, men mangler en rolle for visning av layoutset skal det gis en standard melding om at du ikke har tilgang (selv om dette sannsynligvis skyldes feilkonfigurasjon).

```[tasklist]
## Tasks
- [ ] Implementere støtte for rollesjekk i uttrykk
- [ ] Evaluere uttrykk i id property i layout-set.json
- [ ] Støtte forhåndsvisning av layouts og komponenter i Studio hvor det uttrykk basert på roller
```

## Akseptansekriterier
- [ ] Komponenter kan vises/skjules basert på rolle til pålogget bruker
- [ ] Layout kan vises/skjules basert på rolle til pålogget bruker
- [ ] Layoutset kan velges dynamisk ved hjelp basert på rolle til pålogget bruker
- [ ] Skjuling av komponenter basert på rolle må også støttes i backend for fjerning av skjulte felter
