### ISSUE TITLE
Create component SubFormTable

### ISSUE THREAD

**Issue by HauklandJ** [Altinn/app-frontend-react#2144]
Part of the [Underskjema Epic](https://github.com/Altinn/app-frontend-react/issues/2137)

As a PoC for subforms, add a SubFormTable. This is, as the name implies, a table which subforms can be added to. The experience will be close to that of [Repeating Groups](https://docs.altinn.studio//altinn-studio/reference/ux/fields/grouping/repeating/).

Each SubFormTable will ONLY support SubForms of a single type.

This issue is for the SubFormTable component itself, and it is dependant on other issues linked in the Epic.

Design: [figma](https://www.figma.com/design/rwlLhNgl6wW7ExZMReb4T4/Underskjema?node-id=22-53968&t=FmjX8AR9qH5fvTNy-4), [issue](https://github.com/Altinn/app-frontend-react/issues/1759)

```[tasklist]
### Tasks
- [ ] https://github.com/Altinn/app-frontend-react/issues/2227
- [x] The textResourceBindings.addbutton configuration should represent the full text of the button, not just the last concatenated element
- [x] Disable at least the "add" button, possibly the whole table, while an add or delete request is being processed
- [ ] https://github.com/Altinn/app-frontend-react/issues/2228
```

**Comment by danielskovli** [comment]
Implemented
