### ISSUE TITLE
Consider roadmap requirements

### ISSUE THREAD

**Issue by danielskovli** [Altinn/app-frontend-react#2261]
## Description
The [roadmap issue](https://github.com/digdir/roadmap/issues/290) outlines acceptance criteria and has received comments, which may or may not still be applicable.

Consider these in the light of this particular (stage 1) implementation. Take action as required.

### From acceptance criteria
- [x] Et underskjema vil ha alle de samme mulighetene som et hovedskjema med tanke på sideinndeling, bruk av komponenter, vis/skjul logikk, validering etc.
- [x] Et underskjema vil ha sin egen datamodell og sin egen layout for hvordan skjema skal fremstå for brukeren. I første versjon skal eksisterende sideoppbygging benyttes, men i fremtiden skal det være mulig å velge alternative visninger for enkle underskjema f. eks. en overlay eller embedded direkte i skjema. Sistnevnte er kanskje mest aktuelt i kombinasjon med dashboard funksjonalitet (planlagt i
https://github.com/Altinn/altinn-studio/issues/83)
- [x] Data for underskjema lagres for seg selv og får et eget dataelement
- [x] Man kan opprette mange underskjema av samme type og man kan ha flere forskjellige typer underskjema.
- [x] Fra hovedskjema kan man legge til underskjema gjennom en egen komponent som holder kontroll på underskjemaene.
- [x] ~Man kan enten ha én underskjemakomponent som holder kontroll på alle underskjemaene uavhengig av type, eller~ man kan ha flere underskjemakomponenter som holder kontroll på sine egne typer.
- [x] Det skal være mulig å styre krav til hvor mange underskjema man skal ha av en gitt type (minimum og maksimum).
- [x] Det skal være mulig å lukke redigeringen av et underskjema, selv med valideringsfeil, og fortsette redigeringen på et senere tidspunkt.
- [x] Uttrykk i underskjema må kunne referere til data fra hovedskjema for vis/skjul logikk
- [x] Det skal være mulig å ha en oppsummeringsside som henter data fra både hovedskjema og underskjema.
- [x] Innsening av hovedskjema med tilhørende underskjema må validere alle skjema før innsending kan skje.
- [ ] ~Det skal være mulig å lage egen PDF for underskjema~
- [x] Det skal være mulig å inkludere data fra underskjema i PDF (hvis man bare ønsker en PDF)
- [x] Det skal være mulig å inkludere underskjema i grunnlaget det signeres på.
- [ ] ~Ulike navn på PDF'er~

### From comments
- [ ] ~Det bør vere mogleg å delegera kvart enkelt underskjema~ (out of scope for initial release)
- [ ] ~Mulighet til å styre min/max count dynamisk basert på valg brukeren har gjort i hovedskjema (#2273)~
- [x] Jeg tror også man må kunne dyplenke til en side i et underskjema. Det vil si, hvilket underskjema man står i, og hvilken side man står på der, bør ligge i URLen slik at fremover/tilbake-knappene i nettleseren bør fungere

**Comment by HauklandJ** [comment]
Fra diskusjon om scope på versjon 1:
delegere underskjema - ikke ta tak i i første omgang
kan utsette signatur på underskjema
egen pdf for underskjema - lavest prioritering / utsette
