### ISSUE TITLE
Custom button design in a repeatingGroup/table

### ISSUE THREAD

**Issue by xmrsa** [Altinn/app-frontend-react#2354]
### Description

When creating a custom button in a repeating structure, the button size and color looks strange in comparison with the edit- and save-buttons . In my case the copy-button should have had a design similar to the other buttons on the same row in the table. I only have the two choices "primary" and "secondary", and none of them look user friendly in a table. It should also be possible to adjust the placement of the button so it ends up in connection with the edit- and save-button (or together with the "Save and close"-button. I also wonder about the WCAG issue her. It seams to me that the aria-label should be something more than  "aria-busy=false". Is it possible to set this on the component when I use it?
![image](https://github.com/user-attachments/assets/7e305e45-a35c-4aca-bd78-cf827f41d736)

### Tasks
- [x] variant tertiary for custom button
- [ ] add support for some often-used icons for custom button
- [ ] table title for custom button

### Additional Information

![image](https://github.com/user-attachments/assets/eb26608a-8b71-40c7-a54c-db98e4cf43d9)
![image](https://github.com/user-attachments/assets/0274c9f0-d674-434f-8ee3-0fa63d36b412)
![image](https://github.com/user-attachments/assets/6e0b8b70-22c2-479f-977a-1c7b59b76f00)

**Comment by olemartinorg** [comment]
Vi kan også se på dette i sammenheng med #1164, og om vi kommer frem til at vi vil endre på utseendet på de eksisterende knappene bør vi også sjekke om dette helst bør gjøres til neste major-versjon istedenfor å endre dette for apper som allerede bruker v4. Jeg la på UX-label for å indikere at vi burde prototype en løsning og bli enige om et design først før implementasjonen påbegynnes.

**Comment by hannefinnoy** [comment]
Enig med deg i at det blir rart med primary og secondary her. Her burde vi kunne gjøre det mulig tertiary også. Da blir de like i uttrykket, som på skissen fra Figma under. Her har jeg også lagt inn knapp med kun ikon for å spare plass ref. #1164 
Hva gjør funksjonaliteten "kopier"? Lager en ny rad med samme informasjon? Det blir vel litt rart å kopiere før man har lagret informasjonen man legger inn? 
<img width="967" height="893" alt="Image" src="https://github.com/user-attachments/assets/2dcd35af-e59d-4f6e-9453-2c6f79ce03ea" />
