### ISSUE TITLE
Design for parallell signering i en Altinn app

### ISSUE THREAD

**Issue by olavflar** [Altinn/app-frontend-react#2372]
## Description
Overordnet beskrivelse

Parallellsignering innebærer at flere personer skal signere på et steg i en tjeneste før prosessen flyttes videre til neste steg. Det kan f.eks. være at begge foreldre må signere på noe som gjelder felles barn.

### Forventet resultat

Tilby tilsvarende funksjonalitet som de tjenestene som benytter parallellsignering i Altinn 2 i dag slik at migrering av disse er mulig. Enkel konfigurering av signering, og hvilke roller som skal signere, på et gitt steg i prosesen til en tjeneste.

### Hvordan skal det fungere?

Alle som skal signere vil få et varsel om at de må signere. Den aktuelle siden skal kunne vise hva de signerer på og evt. konsekvenser, dette styres av den enkelte tjenesteeier. Hver enkelt som signerer vil få en kvittering for signeringen samt hva de har signert på.

Parallell signering i Altinn 2 er en oppgave hvor flere brukere trenger eller kan signere dataene parallelt. Oppgaven er fullført når det nødvendige antallet signaturer er lagt til. Denne typen signering er nyttig i scenarier hvor flere godkjenninger er nødvendig før man kan gå videre til neste steg…

#### Her er noen viktige punkter om parallell signering:

1. Flere signatører: Flere brukere er involvert i signeringsprosessen.

2. Samtidig signering: Brukere kan signere dokumentet samtidig.

3. Fullføringskriterier: Oppgaven anses som fullført når det nødvendige antallet signaturer er samlet inn.

For mer detaljert informasjon, kan du se på [GitHub-issue for parallell signering](https://github.com/Altinn/altinn-studio/issues/1325).

#### Slik fungerer det for sluttbrukeren:

1. Varsling: Brukere som må signere vil bli varslet. Dette kan gjøres gjennom ulike varslingskanaler støttet av Altinn, som e-post eller SMS. Varslingen vil informere dem om at det er et dokument eller data som krever deres signatur.

2. Tilgang til oppgaven: Brukere logger inn på Altinn og navigerer til sine oppgaver. De vil se signeringsoppgaven oppført blant sine ventende oppgaver.

3. Gjennomgang av data: Brukere kan gjennomgå dataene som må signeres. Dette sikrer at de forstår hva de signerer.

4. Signering av data: Brukere vil deretter fortsette med å signere dataene. Avhengig av det nødvendige sikkerhetsnivået, kan dette innebære en enkel bekreftelse eller en digital signatur ved bruk av systemer som BankID.

5. Fullføring: Oppgaven markeres som fullført når det nødvendige antallet signaturer er samlet inn. Hvis flere brukere må signere, vil oppgaven forbli åpen til

### In scope

Et design for hvordan man legger til person eller foretak som skal signere 
Hvordan vil det være med roller og tilgangstyring. Mere info her; https://info.altinn.no/hjelp/profil/alle-altinn-roller/paralell-signering/

### Out of scope

I samarbeid med design på tvers så ser vi på hele flyten for flere av appene som er i Altinn - Dette er et pågående arbeid som vil være med å løfte hele opplevelsen av hvordan man utfører oppgaver og fyller ut skjemaer i Altinn - Arbeidsgruppen møtes hver 14 dag vi kommer tilbake til hvordan det arbeidet vil påvirke hvordan vi designer og utvikler. I første versjon av parallell signering vil vi fokusere på det som er inne i appen og hvordan det ser ut der. Men også ta med noen skisser fra hvordan vi kan se for oss flyten, med tanke på ny innboks og arbeidsflate og ny portal  

eSignering er utenfor første versjon. 

```[tasklist]
### Tasks
- [x] Innsiktsarbeid
- [x] Flyt for prosess for signering
- [x] Design av felleskomponent for signering
- [ ] Konsept for hvordan signering fungerer i innboks
- [x] Summary komponenter for signering
- [x] Interaksjonsmønster for å legge til personer og virksomheter
```
