### ISSUE TITLE
Subform: handle targeting a subform layoutset using summary2 to create a summary of the subform

### ISSUE THREAD

**Issue by Magnusrm** [Altinn/app-frontend-react#2413]
See https://github.com/Altinn/app-frontend-react/issues/2339 for original issue description.

## Pull request
https://github.com/Altinn/app-frontend-react/pull/2447

```[tasklist]
### TODOs
- [x] Hide Loader component for subform PDF overrides
- [x] Cleanup debug code
- [x] Test rendering of expression based visibility (moped extra-info)
- [x] Test rendering of multi-page layouts
- [x] Rewrite ReadyForPrint implementation to wait for subform data to be loaded
- [x] Revert SubformSummaryComponent2 debug
- [x] Extend SubformSummaryComponent2 to choose between table view and full-layout render
- [x] Fix cypress tests
```
