### ISSUE TITLE
Improve subform rendering in Summary2

### ISSUE THREAD

**Issue by danielskovli** [Altinn/app-frontend-react#2482]
## Description
Slack thread: https://digdir.slack.com/archives/C076T2293CM/p1727091941170709

```[tasklist]
### Tasks
- [x] Fix spacing between elements in full view (because edit buttons are removed)
- [ ] https://github.com/Altinn/app-frontend-react/issues/2478
- [x] Insert datamodel type + GUID before each subform output in full view
```
