### ISSUE TITLE
Add support in Application frontend for BPMN gateways

### ISSUE THREAD

**Issue by TheTechArch** [Altinn/app-frontend-react#262]
## Description

After the backend now supports gateways frontend need to be updated to do the same

## Considerations

- We need to update App API so that the app frontend knows that there are multiple flows out of the current task. Example. Go back to data from confirmation and confirm. Should also this API indicate if the user is authorized?
- We need to design how the navigation buttons should be placed for returning to the previous task. 
- We need to design how the navigation buttons should be placed for forwarding
- What if there are more than two flows out of a task.
- Do we need a category of flows? 
- Think signing: Should it be a sign button on the back button, or should it maybe be a sign and deny sign? 
- What about authorization. Should buttons be disabled, or should we handle not authorized when clicking

## Acceptance criteria

- [ ] Frontend show button when a flow from the current task is present. This goes for both confirmation and feedback and possible data task.
- [ ] An authorized user can press a button and instance state is then moved to the requested state
- [ ] GUI for that given state is presented
- [ ] Needed state change data updates are performed. (like unlocking data or deleting PDF)

## Specification tasks

- [x] Altinn/app-frontend-react#271 
- [ ] Altinn/app-frontend-react#97 
- [x] Design GUI for the specific tasks. If needed. What if there are more than 2 options? 
- [x] Design GUI for what will happen when a user is not authorized to follow a specific flow. (Disabled button or warning when clicking) [Figma sketches](https://www.figma.com/file/wnBveAG2ikUspFsQwM3GNE/Altinn-Studio-Apps?node-id=15741%3A29639)
- [x] Altinn/app-template-dotnet#129 
- [ ] Development tasks are defined

### 1. If a user filled out a form, but **is not authorized** to confirm: 

**Preferred solution:** 
- The user can select from a list of authorized persons in the organization. The selected person(s) will recive a message in their innbox about a form ready to confirm. 
 
<img width="2493" alt="image" src="https://user-images.githubusercontent.com/1464915/161015397-474c1def-c043-421d-b8eb-a47bd320e7b1.png">

**Possible solution until notification is available:** 
- The user have to confirm that he understands that the data will **not** be sent, just saved for other in the organization with authorization to continue.
- This will NOT be a good solution, since the user might not know who to contact in his organization to get this form signed/confirmed. To make this work, we have to show a static list of 1-3 autorized people in the organization. (When many authorized persons, could it pick someone who recently signed something else/was active?)

<img width="1999" alt="image" src="https://user-images.githubusercontent.com/1464915/161019699-e17f7490-0efe-43db-8e7d-e4df107e063e.png">

### 2. If a user filled out a form and **is authorized** to confirm: 
<img width="2340" alt="image" src="https://user-images.githubusercontent.com/1464915/161020151-45023499-022a-488b-90bc-4bba2356eb35.png">

### 3. If a user recive a form filled out by someone else, and has the permission to both **confirm** and **edit**: 
- A user with rights will see what the previous user filled out and be able to sign, change or send it back: 

<img width="2431" alt="image" src="https://user-images.githubusercontent.com/1464915/161029200-1af3d888-09bb-42d0-97b6-9a4a51f36942.png">

### 4. If a user receives a form filled out by someone else, and has the permission to **confirm** but not **edit**: 

**Preferred solution:** 
- The user will be able to send the form back to the person(s) who filled it out, and also add a comment on what is wrong/should be looked at again. 
<img width="1134" alt="image" src="https://user-images.githubusercontent.com/1464915/161029741-19422db0-8492-4f75-be20-a9a78b57f79e.png">

**Possible solution until notification is available:** 
- When notification is not possible, the button "Send back" should not be visible. The users **has to know** who filled out the form, to make this work as a temporary (not great) solution. 
<img width="1415" alt="image" src="https://user-images.githubusercontent.com/1464915/161029851-043f1b2d-d808-48d0-baff-bfdbd0336730.png">

## BPMN

The below BPMN show how gateways are handled

altinn:flowtype    Defines what type of flow. 
altinn:flowaction  Defines authorization

```xml
<?xml version="1.0" encoding="UTF-8"?>
<bpmn:definitions id="Altinn_SingleDataTask_Process_Definition"
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xmlns:altinn="http://altinn.no"
  xmlns:bpmn="http://www.omg.org/spec/BPMN/20100524/MODEL"
  xmlns:bpmndi="http://www.omg.org/spec/BPMN/20100524/DI"
  xmlns:dc="http://www.omg.org/spec/DD/20100524/DC"
  xmlns:di="http://www.omg.org/spec/DD/20100524/DI"
  targetNamespace="http://bpmn.io/schema/bpmn" >
  <bpmn:process id="TwinDataTaskWithConfirm" isExecutable="false">
    <bpmn:startEvent id="StartEvent_1">
      <bpmn:outgoing>SequenceFlow_1</bpmn:outgoing>
    </bpmn:startEvent>
    <bpmn:task id="Task_1" name="Nabovarsel" altinn:tasktype="data">
      <bpmn:incoming>SequenceFlow_1</bpmn:incoming>
      <bpmn:outgoing>SequenceFlow_2</bpmn:outgoing>
    </bpmn:task>
    <bpmn:task id="Task_2" name="Utfylling" altinn:tasktype="data">
      <bpmn:incoming>SequenceFlow_2</bpmn:incoming>
      <bpmn:incoming>SequenceFlow_6</bpmn:incoming>
      <bpmn:outgoing>SequenceFlow_3</bpmn:outgoing>
    </bpmn:task>
    <bpmn:task id="Task_3" name="Bekreft" altinn:tasktype="confirm">
      <bpmn:incoming>SequenceFlow_3</bpmn:incoming>
      <bpmn:outgoing>SequenceFlow_4</bpmn:outgoing>
    </bpmn:task>
    <bpmn:exclusiveGateway id="Gateway_1" default="SequenceFlow_5">
      <bpmn:incoming>SequenceFlow_4</bpmn:incoming>
      <bpmn:outgoing>SequenceFlow_5</bpmn:outgoing>
      <bpmn:outgoing>SequenceFlow_6</bpmn:outgoing>
    </bpmn:exclusiveGateway>
    <bpmn:endEvent id="EndEvent_1">
      <bpmn:incoming>SequenceFlow_4</bpmn:incoming>
    </bpmn:endEvent>
    <bpmn:sequenceFlow id="SequenceFlow_1" sourceRef="StartEvent_1" targetRef="Task_1" />
    <bpmn:sequenceFlow id="SequenceFlow_2" sourceRef="Task_1" targetRef="Task_2" />
    <bpmn:sequenceFlow id="SequenceFlow_3" sourceRef="Task_2" targetRef="Task_3" />
    <bpmn:sequenceFlow id="SequenceFlow_4" sourceRef="Task_3" targetRef="Gateway_1" />
    <bpmn:sequenceFlow id="SequenceFlow_5" sourceRef="Gateway_1" targetRef="EndEvent_1" />
    <bpmn:sequenceFlow id="SequenceFlow_6" sourceRef="Gateway_1" targetRef="Task_2" altinn:flowtype="AbandonCurrentReturnToNext"  altinn:flowaction="read" />
  </bpmn:process>
</bpmn:definitions>


```

## Development tasks

- [ ] Create API that can indicate for a frontend that there exist several flows. Altinn/app-template-dotnet#129 
- [ ] Update App frontend to check for process possibilties Altinn/app-frontend-react#432 
- [ ] Update frontend to present process navigation. Altinn/app-frontend-react#432
- [ ] Create a secondary button Altinn/app-frontend-react#103

Secondary button:
<img width="670" alt="image" src="https://user-images.githubusercontent.com/1464915/159884271-8555c5a2-327e-42b5-a246-14b9f8bfd5de.png">

## Definition of done

- [ ] Documentation (docs.altinn.studio) is updated (if relevant)
  - [ ] Technical documentation
  - [ ] User documentation
- [ ] QA
- [ ] Manual test is complete (if relevant)
- [ ] Automated test is implemented (if relevant)
- [ ] All tasks in this userstory are closed (i.e. remaining tasks are moved to other user stories or marked obsolete)

**Comment by RonnyB71** [comment]
Løst ifm implementering av gateway støtte.
