### ISSUE TITLE
Guidelines: As an end user I can clearly see who is the owner of this app

### ISSUE THREAD

**Issue by Febakke** [Altinn/app-frontend-react#266]
## Introduction
There is a need both from app owners and end users that our apps can be styled/customized in some way. The main need is to communicate who the responsible app owner is.

## Design proposal
**We change the background color in our apps to a more neutral color.**
Our blue color can be a little too "Altinn" and might take away from who is owning the application. We should also remove the "organization" icon in the header. 

**We should make a new component that communicate to the user who is owning the app**
This component should present the user with the app owners name, logo and color. It could also include contact information and general information about the app. The main goal of this component is to clearly communicate who is behind the app and give them direction if they need help.

**We do not recommend changing the CSS for individual apps that use our Altinn design.**
If we open up our CSS for bigger changes this would hurt the consistency between apps. The consistent design between app owners is something we should strive for. The need here is to communicate with the user who is owning the app. We think it is better to create one solution that can be used and improved by everyone, instead of many different solutions trough CSS changes. One bonus is that it will make it easier for us to control accessibility across apps on our platform.

Advantages if we can maintain a consistent user experience:

> When users encounter an app/service, they bring their own expectations from previous experiences with them. When these expectations are met, confidence is built, and they will know how to interact with the components. When users don’t need to learn new interactions, their focus will be entirely on the apps content and messaging.

[NN/g](https://www.nngroup.com/articles/consistency-and-standards/)

## Acceptance criterea 
- [x] Background color changed
- [x] navigation buttons fixed
- [x] Fix header 
  - [x] change color
  - [x] service owner
  - [x] remove corp icon  
 - [x] Footer with contact info

## In scope
- [x] Decide on solution
- [x] Design component
- [x] Mobile design
- [x] specify new background color

**Comment by altinnadmin** [comment]
#138

**Comment by FinnurO** [comment]
Footer is done

**Comment by RonnyB71** [comment]
I'm closing this as all tasks are done within the scope of this epic. However a more extended version with theming support will be created to allow for even more standard customization and alignment with a service owners design system.
