### ISSUE TITLE
Remove last remnants of old @altinn/altinn-design-system

### ISSUE THREAD

**Issue by cammiida** [Altinn/app-frontend-react#2788]
### Description

Refactor last components from `@altinn/altinn-design-system`. This includes:

Depending on #2631 

### Tasks
Refactor:
- [x] Pagination (move our own wrapper in `app-components`?)
- [x] DescriptionText (belonging to Pagination)
- [ ] AppWrapper: can be removed when the aforementioned components are removed. May cause css classes to disappear, so make sure all places using the old css classes are changed to the new one. 

### Acceptance Criterias
- Designers are happy with the new pagination look
- No other UI is broken. (Percy)

**Comment by paal2707** [comment]
There is a new pagination component from designsystemet that we get available if we upgrade the version of designsystemet. We should check this out.
