### ISSUE TITLE
Show warning message for uses where there are large groups that are being deleted

### ISSUE THREAD

**Issue by Febakke** [Altinn/app-frontend-react#321]
When trying to delete a row in our repeating groups the user should get a warning. 

## Sketches
![Skjermbilde 2022-07-05 kl  14 41 57](https://user-images.githubusercontent.com/33222679/177329956-ae108e61-36df-4189-a284-75d1d944e4af.png)
[Figma prototype](https://www.figma.com/proto/wnBveAG2ikUspFsQwM3GNE/Altinn-Studio-Apps?page-id=2090%3A6723&node-id=13550%3A9415&viewport=1436%2C-7265%2C0.22&scaling=scale-down&starting-point-node-id=13550%3A8883&show-proto-sidebar=1)

## Criterea
- [ ] When trying to delete the user gets a warning
- [ ] The app developer can decide if this is needed. Might be overkill for small groups

## Tasks
- [x] New modal in design system using the panel?
- [ ] Implement logic in app-frontend
