### ISSUE TITLE
Considerations for v4

### ISSUE THREAD

**Issue by haakemon** [Altinn/app-frontend-react#339]
# Description
After `v3` comes `v4`. This issues lists changes we need to (or want to) complete in the breaking changes window for `v4`.

```[tasklist]
### Breaking changes
- [ ] https://github.com/Altinn/app-frontend-react/pull/1446
- [ ] https://github.com/Altinn/app-frontend-react/pull/1441
- [ ] https://github.com/Altinn/app-frontend-react/pull/1444
- [ ] https://github.com/Altinn/app-frontend-react/issues/1148
- [ ] https://github.com/Altinn/app-frontend-react/issues/975
- [ ] https://github.com/Altinn/app-frontend-react/issues/820
- [ ] https://github.com/Altinn/app-frontend-react/issues/1468
- [ ] https://github.com/Altinn/app-frontend-react/issues/1485
- [ ] https://github.com/Altinn/app-frontend-react/issues/1486
- [ ] https://github.com/Altinn/app-frontend-react/issues/628
- [ ] https://github.com/Altinn/app-frontend-react/issues/1487
- [ ] https://github.com/Altinn/app-frontend-react/issues/1488
- [ ] https://github.com/Altinn/app-frontend-react/issues/1489
- [ ] https://github.com/Altinn/app-frontend-react/issues/1491
- [ ] https://github.com/Altinn/app-frontend-react/issues/1493
- [ ] https://github.com/Altinn/app-frontend-react/issues/1495
- [ ] https://github.com/Altinn/app-frontend-react/issues/1496
- [ ] https://github.com/Altinn/app-frontend-react/issues/1500
- [ ] https://github.com/Altinn/app-frontend-react/issues/1502
- [ ] https://github.com/Altinn/app-frontend-react/issues/1512
```

```[tasklist]
### Data model related changes
- [ ] https://github.com/Altinn/app-frontend-react/issues/1175
- [ ] https://github.com/Altinn/app-frontend-react/issues/555
- [ ] https://github.com/Altinn/app-frontend-react/issues/1484
- [ ] https://github.com/Altinn/app-frontend-react/issues/273
- [ ] https://github.com/Altinn/app-frontend-react/issues/925
- [ ] https://github.com/Altinn/app-frontend-react/issues/1111
- [ ] https://github.com/Altinn/app-frontend-react/issues/1147
- [ ] https://github.com/Altinn/app-frontend-react/issues/707
- [ ] https://github.com/Altinn/app-frontend-react/issues/743
- [ ] https://github.com/Altinn/app-frontend-react/issues/1104
- [ ] https://github.com/Altinn/app-frontend-react/issues/1490
- [ ] https://github.com/Altinn/app-frontend-react/issues/1501
```

```[tasklist]
### Features, non-breaking and others
- [ ] https://github.com/Altinn/app-frontend-react/issues/754
- [ ] https://github.com/Altinn/app-frontend-react/issues/133
- [ ] https://github.com/Altinn/app-frontend-react/issues/726
- [ ] https://github.com/Altinn/app-frontend-react/issues/1294
- [ ] https://github.com/Altinn/app-frontend-react/issues/1094
```

**Comment by olemartinorg** [comment]
I'm also throwing #220 in here. I'm starting to look at bringing this type of functionality (expressions in layout, specifically) into some parts of the frontend in #355 now, but the way we prototyped in #220 meant it would be a breaking change.

**Comment by olemartinorg** [comment]
Adding a few more issues. Right now it's possible to define a [filter for a group component](https://docs.altinn.studio/app/development/ux/fields/grouping/alternatives/#filter), which can be used to filter out certain rows if they match a value in the data model. It is also possible to define a [start/stop index](https://docs.altinn.studio/app/development/ux/components/likert/#filter-out-questions-with-start-and-end). Showing/hiding rows should [use proper dynamics instead](https://github.com/Altinn/app-frontend-react/issues/389), preferably by [extending expressions](https://github.com/Altinn/altinn-studio/issues/8799).

**Comment by xmrsa** [comment]
Dette forklarer problemene jeg opplevde i mitt skjema, jamfør Slack: https://altinn.slack.com/archives/C02EVE4RU82/p1666346435963569

**Comment by StianVestli** [comment]
org/ssb

**Comment by olemartinorg** [comment]
@StianVestli Jeg dropper å tagge dere på dette issuet, siden det bare er en samling av ting vi bør tenke på til neste major-versjon (og dermed er ikke dette noe vi skal "gjøre") - vi kan heller tagge dere på de spesifikke sakene.

**Comment by StianVestli** [comment]
Skeptisk til at man vil fjerne pageorder funksjonaliteten, siden denne gir oss muligheten til å manipulere data, og gjøre større endringer , endre rekkefølge på sidene osv, det går ikke med ny dynamikk. Da er er det bedre å si at man ikke kan kombinere dynamisk skjuling og pageorder. Eller om man kan manipulere Hidden propertyen via c# koden i pageorder. Fordlene med dynamikken er at den gjenspeiles i summary, det gjør ikke pageorder.

**Comment by olemartinorg** [comment]
@StianVestli Vi bør ikke ha to måter å gjøre det samme på. Den eneste fordelen jeg har sett med PageOrder er endring av rekkefølge, og potensielt det faktum at man må styre når det trigges (slik at man f.eks. kan skjule siden man står på i det øyeblikket man går til neste). Rekkefølge tenker jeg vi kan styre på andre måter. I dag finnes det opsjoner man kan sette på en layout som styrer hva som skal være neste og forrige side fra der man står, og i fremtiden tenker jeg det bør kunne styres med dynamikk. Uansett, litt av tanken med neste major-versjon er at vi rydder opp i eget hus - og det inkluderer å fjerne kode istedenfor å ha "både og"-funksjonalitet slik som dette.

Viktigst av alt: Om vi ikke får på plass alternativer som dekker alle eksisterende use-case kan vi naturligvis heller ikke fjerne funksjonalitet, nei.

**Comment by olemartinorg** [comment]
Work has now started, and the changes are currently kept in the [`next`](https://github.com/Altinn/app-frontend-react/tree/next) branch.

**Comment by bjosttveit** [comment]
Another consideration.

I think the "Group" concept should be more general, and that perhaps there should be several components that can have child components. For example, there could be an abstract subclass that all such components implement, that will be used to build the node hierarchy. Today, the `Group` type is hardcoded as the only such component.

With this in mind, I would like to see the current `Group` component split into several separate components. Today, the `Group` component is rendered using three different React components depending on some props:
1. Repeating group: if `maxCount` > 1.
2. PanelGroupContainer: if `panel` is not null/undefined. Used for adding new elements to another repeating group with a groupReference, or simply as a group with a background color if no groupReference is specified.
3. DisplayGroupContainer: otherwise. Plain old group with an optional title, makes it easier to create a Summary of a collection of components if fine grained control is not necessary.

To make this work, there is a `GroupRendererer` component that uses the appropriate react component depending on the props, this logic also needs to be implemented separately in the `SummaryComponent`. This is not currently implemented for the panel case, and will probably just be rendered the same way as a plain group.

This makes the `Group` component needlessly complex, and a lot of logic to check the type of `Group` component is required in many different places to make sure it behaves as expected. This all needs to be maintained during refactoring to make sure no weird use cases break. I think it is a bad idea to keep extending this component and increasing its complexity as opposed to creating several "Grouping" components with a more specific purpose for each.

Therefore, in a new major version, I would like to split the `Group` component into for example:
- `RepeatingGroup`
- `Group` (plain group, maybe with options for styling as a panel)
- Some third component to deal with the use case of adding data to another repeating group (please suggest an appropriate name)

This could be implemented in a way that most of the logic reside within the component classes, so that they are responsible for building and maintaining their sub-trees in the hierarchy. Maybe with common interfaces for getting all of their children and performing validations against their children.

**Comment by olemartinorg** [comment]
Re: https://github.com/Altinn/app-frontend-react/pull/1449, we should also make sure to detect the backend version and deny running on older/legacy backend versions. I'm hoping we can check for [multipart-saving support on the backend](https://github.com/Altinn/app-lib-dotnet/issues/187) for this, if that gets implemented on the backend any time soon - otherwise have have no reliable way of checking.
