### ISSUE TITLE
Upgrade to React-Router v6

### ISSUE THREAD

**Issue by mjulstein** [Altinn/app-frontend-react#353]
### Description

We aim to have a modern and up-to-date code-base.
As well as comply with modern standards and requirements.
Therefore it is time to upgrade to React-Router v6.

### Tasks

- [ ] Follow the migration steps from Router v5 to router to Router v6

### Acceptance Criterias
- [ ] Make sure all Unit-tests still work
- [ ] Verify that Cypress-tests still work
