### ISSUE TITLE
Write cypress test for typing characters into numeric fields

### ISSUE THREAD

**Issue by olemartinorg** [Altinn/app-frontend-react#394]
### Description

A side effect of our number formatting seems to be that typing characters into the field is impossible. The number formatting rules seem to discard any invalid characters (even minuses? maybe that's a bit much). Right now our cypress test for number formatting test that the minus disappears, but it does not explicitly test the expected formatted value.

We should improve this test to make testing for the number formatting more explicit. See tasks for some suggestions on what to test.

### Tasks

- [ ] Make sure it is impossible to type regular characters, and that these are stripped away from the field value. This behavior should perhaps also be implemented for fields that are supposed to be numeric according to the JsonSchema, but are missing number formatting. Consider UX as well, as we might want a dismissable soft validation if the user continues trying to type text into numeric fields.
  - [ ] Consider if we should broaden this issue to implement generic support for limiting the possible input a user can type into a field  
- [ ] Test various permutations of trying to break the formatting by selecting and overwriting characters produced by the formatting operation (i.e. selecting and trying to change the prefix/suffix/thousands separator/comma). See #294.
  - Tip: It could be useful to run `cy.interceptLayout()` and refresh the page to intercept and manipulate the formatting rules in this test, to make sure we cover more use cases.

**Comment by olemartinorg** [comment]
Closing this, consider these tasks moved to #288 (no need for this duplicate)
