### ISSUE TITLE
Navigate from confirmation step to other steps in a process (BPMN)

### ISSUE THREAD

**Issue by mjulstein** [Altinn/app-frontend-react#432]
### Description
As a user I need to be able to navigate back to a previous process task when I have reached the confimation task, so that I can fix what blocks me from submitting.

This is a specification of the frontend tasks from Altinn/app-frontend-react#262 
In issue Altinn/app-template-dotnet#129 a new endpoint is discussed.
The gist is that this endpoint can be called on the start of any given processes-task and the backend will respond with tasks that are available to the client at a given time in the process.

The API should return enough information about the process so that a call to `process/next/<requiredInfo:takID?>` will cause the backend to update the process state and the user can be redirected to the root of the App.

### Additional Information

In addition the enabling custom navigation to other processes from a given process we need:
- [ ] Cypress tests to validate that navigating to a given process-task works as intended

A new receipt page is in development by @lorang92 and should work with the overriding button layout.
- <Link to the issue>

### Tasks

In order for this to work we need:
- [ ] Designs on how the overriding button layout should be presented (if the user has access or not) @Febakke  we need to discuss conditional states/access
- [ ] Find a suitable file or create a new one to hold the configuration needed to override the 'submit-button-only' design
- [x] Decide what is actually needed to set up in the new configuration.
   * Is a config actually needed, can we find enough information from the API from Altinn/app-template-dotnet#129 to render additional buttons?
   * If that is the case can we make a unique text-id-prefix for process-next-api buttons that can be localized? WYDT @RonnyB71 ?
   * Can we avoid requiring App developers to edit their configs to utilize the new feature
   * Should we avoid adding this feature unless explicit settings have been applied in the App (the available-next-tasks api could possibly be enough, as it can return 404 if the feature is not available.)
   * Other things

### Acceptance Criterias

- [ ] Buttons are rendered on the receipt-page(s) per the final design
- [ ] The buttons that can be used are functioning as intended: If disabled, you won't change processes etc.
- [ ] Document how to override the current submit-button functionality with this feature
- [ ] Unchanged apps should appear as before
- [ ] When a user is sent to a different process the browser history should be replaced with the page they are currently on while navigating backwards.
