### ISSUE TITLE
Make it possible to share a link to a page inside an active data task

### ISSUE THREAD

**Issue by mjulstein** [Altinn/app-frontend-react#446]
### Description
When I get a link to a page inside a data-task I do not have enough information to go to a specific page.
## TODO:
- [ ] Add the page id to the end of the end of the path so we know what page we want to link to.
- [ ] Use the page id from the url-path to go to the correct page in the flow.
- [ ] If the page you are trying to reach is not there a simple 404 can be rendered for now.
## Related tasks
- [ ] If the page is not available by using Browser History should be solved in #225 (Current idea is to redirect forward to the page you pressed back from, this will recursively wipe the back-history until a valid path is reached in the history)
