### ISSUE TITLE
Replace Checkbox + Radio usage with Design System components

### ISSUE THREAD

**Issue by haakemon** [Altinn/app-frontend-react#507]
### Description

We finally have a [Checkbox in our Design System](https://designsystem.altinn.studio/?path=/story/components-checkbox--normal&globals=backgrounds.value:transparent) package, along with [Radio](https://github.com/Altinn/altinn-design-system/pull/212)s

We should replace any checkboxes and radios in app-frontend with these components

### Additional Information

- https://github.com/Altinn/altinn-design-system/issues/86
- https://github.com/Altinn/altinn-design-system/pull/212

### Tasks

- [ ] Replace MUI checkbox with our DS component
- [ ] Replace MUI radio with our DS component
- [ ] Replace any other checkbox implementation (if any) with our DS component
- [ ] Replace any other radio implementation (if any) with our DS component
- [ ] Dont forget to remove any related styles etc. that are no longer needed

**Comment by olemartinorg** [comment]
@Magnusrm Make sure you also look over #753 when implementing this.

**Comment by bjosttveit** [comment]
Maybe also check if #21 is still an issue.

**Comment by olemartinorg** [comment]
Structuring related issues:
- #753
- #21 
- #728
- #194
- #817 (this one is new!)
