### ISSUE TITLE
Technical debt: Clean up this repo after moving

### ISSUE THREAD

**Issue by olemartinorg** [Altinn/app-frontend-react#552]
This repo was moved out from `altinn-studio` earlier this year, but there's still a lot of remnants from that complexity we should clean up and simplify:

- We have multiple `package.json` files, but should only need one
- The `src/shared` folder used to be shared between different projects, but changes to this folder is no longer kept in sync with `altinn-studio`. We should swallow this code into a single project instead. If code needs to be shared across repos, we should create relevant packages instead (I see no urgent need for this yet).
- Flatten the folder structure (no need for `src` inside `src`, etc)
- Change the github workflows to match

### Tasks

- [x] Combine both `src` folders
- [x] Make unit tests work again
- [x] Make cypress tests work again
- [x] Make sure builds work correctly
- [x] Make sure webpack-dev-server work correctly
- [x] Update build script + github workflow
- [x] Update unit test github workflow
- [x] Update cypress github workflow
- [x] Move `package.json` to root (add cypress)
- [x] Move `tsconfig.json` to root
- [x] Make sure docker compose still work
- [x] Make sure code coverage paths work for SonarCloud
- [x] Go over README.md and correct paths
- [ ] Run prettier and all tools on all the code (including cypress tests and schema jsons?)
