### ISSUE TITLE
Repeating groups: Behavior and UI changes

### ISSUE THREAD

**Issue by Febakke** [Altinn/app-frontend-react#59]
## Description
There are some aspects of the repeating group component that should be configurable by the app developer

1. #61 
2. #62 
3. #64 
4. #68 

Can some of this be combined with this: Altinn/app-frontend-react#60 

Issues taken from Brg related issue #60 and essential for their Reelle rettighetshavere:
1. #243 
2. #322
3. #324
4. #321
5. #323
6. #327 
## Specification tasks

- [ ] Are there more needs that are not covered here?
- [ ] if relevant: Design 

## Definition of done

- [ ] Documentation (docs.altinn.studio) is updated (if relevant)
  - [ ] Technical documentation
  - [ ] User documentation
- [ ] QA
- [ ] Manual test is complete (if relevant)
- [ ] Automated test is implemented (if relevant)
- [ ] All tasks in this userstory are closed (i.e. remaining tasks are moved to other user stories or marked obsolete)

**Comment by rvessb** [comment]
•	Change column header title to something not connected to a form component
> Label på felter I gruppen kan ofte være litt lenger enn bare «beløp» eller «navn», ofte er label en spørsmålsformulering. Da det blir det rart å ha spørsmålsteksten som kolonneheader i tabelloversikten ønsker vi å kunne skreddersy kolonneoverskriftene der det er nødvendig.

•	Custom title for each row generated based on input in the group.
> Vi tenkte at man kunne ha en egen kolonne i tabelloversikten der man gjennom beregninger i kode satte for eksempel «ferdig utfylt» og «ikke utfylt». Denne vil jeg si er godt dekt ( og UU-ivaretat) med https://github.com/Altinn/app-frontend-react/issues/62.

**Comment by Febakke** [comment]
@rvessb 
Har laget en oppgave etter min forståelse av første punktet du nevner her #68 
Du får gi meg beskjed om jeg har bommet helt.

**Comment by RonnyB71** [comment]
Closing epic with one potential leftover (https://github.com/Altinn/app-frontend-react/issues/62) but this is a new concept that we will revisit in subform support.
