### ISSUE TITLE
Datepicker: Clean up and modernize validations

### ISSUE THREAD

**Issue by olemartinorg** [Altinn/app-frontend-react#600]
### Description

The `Datepicker` component suffers from validation duplication, as it keeps validation messages both locally and in Redux. The function `validateDatepickerFormData` is called both in `validation.ts` and in `DatepickerComponent` - but we should aim to keep the validation state in redux only.

### Additional Information

- #185
- #98
- #377

### Tasks

- [x] Remove duplicate/local validation in `DatepickerComponent.tsx`, move missing validation into `validation.ts`
- [x] Implement delayed saving with `useDelayedSavedState` if useful
- [x] Make sure required field validation does not run immediately if field is empty (should only run when clicking `next`)
- [x] Make sure validation works when Datepicker is in a repeating group

**Comment by olemartinorg** [comment]
Tested, working wonderfully!
