### ISSUE TITLE
Automatically generate PDF from layout

### ISSUE THREAD

**Issue by RonnyB71** [Altinn/app-frontend-react#710]
### Description

As a user I would like to have a PDF to serve as a receipt for my submitted form data so that I have a copy of what's sent in.

As a app developer I would like to have the PDF layout generated automatically based on my existing page layout(s) so that I don't have to do anything special in order to serve a PDF for the end user, but I would like to be able to override it if I am not happy with the default.

### Additional Information

Epic: https://github.com/Altinn/app-lib-dotnet/issues/63
Backend:

### Tasks

- [x] Create a page that automatically concatenates the existing layouts to serve as the foundation for the PDF the page is triggered by adding pdf=1 to the query parameters of a regular instance url.
- [x] Ensure the excludeFromPdf flag is still respected on both page and component level
- [x] Make sure the generated page removes components like buttons/navigational elements not relevant for print including summary components
- [x] Provide an easy way to specify a specific page to be used instead of the auto generated page by setting mode=pdf on the page object

**Comment by bjosttveit** [comment]
Does the front-end currently get `excludeFromPdf` (layout-level) from `Settings.json`?

**Comment by bjosttveit** [comment]
Started working on the branch `pdf-page`, made a simple PoC that concatenates layouts and generates summary components. Currently, there is no respect for `excludeFromPdf` as I am not sure this is available to the front-end currently. Currently, it shows headers and paragraphs like normal using `GenericComponent` (not sure if this needs to be included 🤷 ) and other components using `SummarySwitch`. Navigation related components are excluded. There is no custom styling or front page with instance data yet.


![Image](https://user-images.githubusercontent.com/47412359/205903170-3e1f3143-ae9e-4cf2-9b61-4dd71400643e.png)

**Comment by bjosttveit** [comment]
There are currently several issues related to page-breaks with components getting cut off. Some of this may be due to all summary-components using the material-ui Grid as a wrapper (this adds some layout related styling).

**Comment by bjosttveit** [comment]
![Image](https://user-images.githubusercontent.com/47412359/207061579-ff9bc0fc-4cb8-4157-a9d8-f6c7c5c743f6.png)

**Comment by olemartinorg** [comment]
Relevant issues we should look into here:
- #258 
- #445
- #120 (this button should perhaps be modified to print this page?)
