### ISSUE TITLE
Design a first version default template for our new App receipt

### ISSUE THREAD

**Issue by Febakke** [Altinn/app-frontend-react#769]
### Description

As our receipt will use the same front-end components as the rest of our apps we need a design that will support this. This means that we must be able to build the template with the same components that we use to build any other page in our apps. This will make it much easier for our app-developers to edit this page. 

This is the app receipt. The green page that the user sees after they press "send in"
<img width="742" alt="Skjermbilde 2022-12-21 kl  12 54 08" src="https://user-images.githubusercontent.com/33222679/208902925-00cd4d9a-558d-465f-9339-a65be080ab66.png">

NB: The changes to this solution will not change the platform receipt. This is the receipt that is available for the user in their Altinn Archive after an instance is finished. 

### Tasks

- [ ] What elements should be / or must be a part of our new template
  - [ ] "Kvittering" Header 
  - [ ] `<h2>` header
  - [ ]  Metadata table
  - [ ] Link to archive
  - [ ] Standard description text
  - [ ] "The following is sent in" and pdf
  - [ ] Attachments
- [ ] Create a new design based on our app components
