### ISSUE TITLE
Add Cypress-tests for Map component

### ISSUE THREAD

**Issue by olemartinorg** [Altinn/app-frontend-react#813]
### Description

The `Map` component works, and is used in apps. Still, there are no cypress tests for it, so functionality in the component might stop working at some point if something should break. We've already had issues with a change in the design system that threatened to break the image marker in the Map component, but that potential breakage was stopped before it had any damaging effects.

### Additional Information

- https://github.com/Altinn/altinn-studio/issues/8480
- #807 
- https://github.com/Altinn/altinn-design-system/pull/215
- https://github.com/Altinn/altinn-design-system/pull/216
- https://github.com/Altinn/altinn-design-system/pull/250
- https://github.com/Altinn/altinn-design-system/pull/244

### Tasks

- [ ] Test clicking a point in the map, and that it puts some data into the data model
- [ ] Test dragging the map one 'world' over, and that the coordinates wrap
- [ ] Test that image loading is successful for the marker icon (and the shadow/retina file)
- [ ] Test the summary view for the component

**Comment by bjosttveit** [comment]
We should maybe consider moving the Map component from `altinn-design-system` into this repo to make it easier to maintain dependencies (leaflet) and the implementation of our specific functionality. Is this component even used anywhere but `app-frontend-react`?

**Comment by olemartinorg** [comment]
Closing this as done now, as we've had a Cypress test for this for a while now.
