### ISSUE TITLE
Design new concept for form navigation

### ISSUE THREAD

**Issue by mrosvik** [Altinn/app-frontend-react#97]
As a user I would like a clear back and forth navigation between pages in an app, so that I can change my answers later in the process.

We should have one consistant way of showing navigation. We should avoid using multiple main buttons on a single page, because having more than one main call to action reduces their impact, and makes it harder for users to know what to do next. 
- [ ] Some users has been confused about what the back button does when its placed above the app title. The back button should be placed together with a next-button to indicate that you can navigate both back and forward between pages.
- [ ] It should be possible to see all of the pages inside an app, and navigate directly to a specific page.
- [ ] If you navigate from page 1 to page 5, and there was required fields in page 3, that page should turn red with an exclamation mark in the overview of pages.
- [ ] If you completed all required fields in some pages, they should turn green with a checkmark in the overview of pages.

Link to [Figma](https://www.figma.com/design/H8J6PX62LIUqmHxftCWw2D/Navigasjon-i-skjema?node-id=540-43050&t=xJA51kqB1LcPqdRl-1) 

<img width="1453" alt="image" src="https://user-images.githubusercontent.com/1464915/207340966-2cf8c841-bcc6-41ec-b58f-41ee9f0248e7.png">

### Updated task list

- [x] Prepare prototype of navigation for user testing
- [x] Plan and conduct user tests
- [x] Prepare stepper component for Design system
- [x] (Possibly necessary) Design alternative version for Apps with their respective requirements

```[tasklist]
### Tasks
- [ ] https://github.com/Altinn/app-frontend-react/issues/2231
- [ ] https://github.com/Altinn/app-frontend-react/issues/2232
- [ ] https://github.com/Altinn/app-frontend-react/issues/2233
- [ ] https://github.com/Altinn/app-frontend-react/issues/2234
```

**Comment by SimenRokaas** [comment]
Hei, hva er planen for denne saken - er det noe håp om å få inn dette i nærmeste fremtid?
Legg gjerne til DSB som label på denne også.

**Comment by olavflar** [comment]
![Image](https://github.com/Altinn/app-frontend-react/assets/70377508/88880d9e-a29f-4ab5-b93c-5d38e3260d3d)

**Comment by olavflar** [comment]
<img width="502" alt="Skjermbilde 2023-11-09 kl  14 44 56" src="https://github.com/Altinn/app-frontend-react/assets/70377508/8f380bd0-c091-42b1-be61-6850274caec1">

**Comment by Camulos** [comment]
Would be helpful with examples that has a lot of pages (20+) and with only 2-3. Also the steps should have some sort of "completed" indicator, or even an indicator for unanswered questions.

How would the indicator function/animate or in other ways show when additional steps is added?

**Comment by RonnyB71** [comment]
This issue should also be taken into account: https://github.com/Altinn/app-frontend-react/issues/1724

**Comment by olemartinorg** [comment]
Closing this as #2611 is now done
