### ISSUE TITLE
Support summary component in another step

### ISSUE THREAD

**Issue by RonnyB71** [Altinn/app-frontend-react#996]
### Description
Currently it is not really possible to use `Summary` on a confirmation step. In the examples in the documentation, a new component that is readOnly is instead used. We would rather like to support the summary view. The problem with this currently, is that the layout of the data step is not available, and so there is no natural `componentRef`.

It is not obvious how this should be solved, some alternatives are:
1. Configure a "new" component, and somehow set its rendering mode to summary instead.
  - Simple "renderAsSummary": true.
2. Have the summary component refer to the datamodel instead of a different component.
  - Challenges: how do you configure the component settings.
3. Reference the layout and components of a previous step
4. Render summary when the task-type is confirmation.
  - Challenges: Goes against our wish to make tasks less "type dependent".

After a brief discussion we agreed to move on with alternative 1. This means we are extending the the actual components with a summary mode in addition to read and write. At the same time pushing some of the summary component specific settings that exists today until we know more about the needs.

Summary on a separate task than the one used to fill in the data serves a slightly different purpose than having a summary as the last page of a form. On the last page of a form the purpose is to quickly review the form and the values allowing to go back and correct the values. Summary on later step is about reviewing the data in order to make a decision and you might not even av access to modify the data. A decision in this case is to sign or reject based on the values provided effectively moving the process.

### Additional Information
- Edit options should be disabled as the previous step is completed. Other actions might set the process back allowing for editing. But the summary on a confirm step should probably be read only.

### Tasks
- [x] Identify all components that should have a summary mode
- [ ] Implement summary mode on identified components
- [ ] Document the setup and configuration and any differences with regards to the summary component

### Acceptance Criterias
- [ ] Ability to create a layout with components setting the mode to summary
- [ ] Trying to pass data updates to the server should return a Forbidden response

**Comment by olemartinorg** [comment]
I agree most with this suggestion:

> Configure a "new" component, and somehow set its rendering mode to summary instead.

Although there are specific configuration options for summary components as well, so we might lose some of those with a simple `"renderAsSummary": true`.

I have also made the suggestion that it's possible to duplicate a layout, add it to the confirmation step, but exclude it from the page order (effectively hiding it). It might then be possible to use such a component in an implicitly hidden layout to render a summary.

We're also expecting an issue/feature request for showing a Summary component even if the source component is hidden.

We might also want to go in a direction where the confirmation step layout-set includes/extends the previous step layout-set, such that previous layouts are also loaded (but hidden). That way you could refer to previous components.
